# Welcome to last session of this Module!! 

![meme](https://cdn-images-1.medium.com/max/1200/1*UKIHA2AHtB9WPG-KrfwSZg.png)

# Revision Questions

## Probability Distributions

---

**1. System Failures**

**Manager's Query**: "Our system fails on average every 50 operations. What's the likelihood of it failing on the very next operation?"


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


**Observed Data**: λ = 1/50

**Solution**: Geometric Distribution
```python
from scipy.stats import geom
probability = geom.pmf(1, p=1/50)
```

---

**2. Server Downtime**

**Manager's Query**: "On average, our server goes down once every 100 hours. What's the probability it will go down in the next 30 hours?"


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



**Observed Data**: λ = 1/100

**Solution**: Exponential Distribution
```python
from scipy.stats import expon
probability = expon.cdf(30, scale=100)
```

---

**3. Vaccine Efficacy**

**Manager's Query**: "Our vaccine has an efficacy of 90%. If we vaccinate 200 individuals, how likely is it that all 200 individuals are protected?"


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



**Observed Data**: n = 200, p = 0.9

**Solution**: Binomial Distribution
```python
probability = binom.pmf(200, n=200, p=0.9)
```

---

**4. Network Outages**

**Manager's Query**: "On average, our network experiences 2 outages per day. How likely is it to experience 4 outages in the next day?"


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



**Observed Data**: λ = 2

**Solution**: Poisson Distribution
```python
probability = poisson.pmf(4, mu=2)
```

---

**5. Delivery Times**

**Manager's Query**: "On average, we deliver packages in 5 days. What's the probability that a package will take more than 7 days to deliver?"


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



**Observed Data**: λ = 1/5

**Solution**: Exponential Distribution
```python
probability = 1 - expon.cdf(7, scale=5)
```

---

**6. Factory Product Failures**

**Manager's Query**: "In our factory, there is a 2% chance a product will be defective. If we produce 500 products in a day, what is the probability that more than 15 products will be defective?"


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



**Observed Data**: n = 500, p = 0.02

**Solution**: Binomial Distribution
```python
probability = 1 - binom.cdf(15, n=500, p=0.02)
```

---

**7. Customer Support Response Time**

**Manager's Query**: "On average, a customer support ticket is resolved in 3 days. How likely is it that a ticket will be resolved in less than 1 day?"


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



**Observed Data**: λ = 1/3

**Solution**: Exponential Distribution
```python
probability = expon.cdf(1, scale=3)
```

---

**8. Sale Conversions**

**Manager's Query**: "On average, every 20th visitor to our website makes a purchase. What's the probability that the next sale will only happen after the 30th visitor?"


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



**Observed Data**: p = 1/20

**Solution**: Geometric Distribution
```python
probability = geom.pmf(30, p=1/20)
```

---

**9. Marketing Campaign Success Rate**

**Manager's Query**: "From previous campaigns, we know that 5% of users exposed to an ad end up purchasing a product. If 1000 users are exposed to our new ad, what's the probability at least 60 will make a purchase?"


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



**Observed Data**: n = 1000, p = 0.05

**Solution**: Binomial Distribution
```python
probability = 1 - binom.cdf(59, n=1000, p=0.05)
```

---

**10. Email Responses**

**Manager's Query**: "Typically, we receive a response every 25 emails we send. How likely is it that we'll get a response on the very next email we send out?"


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



**Observed Data**: p = 1/25

**Solution**: Geometric Distribution
```python
probability = geom.pmf(1, p=1/25)
```

---

**11. Customer Feedback Collection**

**Manager's Query**: "On average, 1 in every 50 customers provides feedback on our service. What's the probability that we'll have to wait for 60 customers before receiving feedback?"


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



**Observed Data**: p = 1/50

**Solution**: Geometric Distribution
```python
probability = geom.pmf(60, p=1/50)
```

---

**12. Customer Interactions**

**Manager's Query**: "On average, we receive 8 customer interactions (calls, emails) per hour. What's

 the probability we'll receive exactly 10 customer interactions in the next hour?"


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



**Observed Data**: λ = 8

**Solution**: Poisson Distribution
```python
probability = poisson.pmf(10, mu=8)
```

---

# How Fit, Transform and Fit_Transform works in sklearn?


### 1. `fit`
The `fit` method is about understanding, learning, or calculating properties from the training data that will be useful later, typically for transformation or prediction. It doesn't modify the data. For many scikit-learn objects, this is where the "learning" happens if it's a machine learning model, or where properties are computed if it's a transformer.

#### SimpleImputer example with `fit`:
Imagine we have some data with missing values and we want to fill them with the mean value of the column. The `fit` method, when applied on this data, will compute the mean for each column and store it inside the imputer object.

In [20]:
from sklearn.impute import SimpleImputer
import numpy as np

data = [[1, 2], [np.nan, 3], [7, 6]]
imputer = SimpleImputer(strategy='mean')
imputer.fit(data)

# The imputer has now computed and stored the mean for each column.
print("Means:", imputer.statistics_)

Means: [4.         3.66666667]


### 2. `transform`
The `transform` method takes in data and returns a new version of the data after applying the transformation. The nature of the transformation depends on the specific algorithm or technique of the transformer or model.

#### SimpleImputer example with `transform`:
Using the previously `fit` imputer, you can now call `transform` on new data to fill missing values with the computed mean.

In [21]:
new_data = [[np.nan, 10], [5, np.nan], [6, 7]]
filled_data = imputer.transform(new_data)

print(filled_data)

[[ 4.         10.        ]
 [ 5.          3.66666667]
 [ 6.          7.        ]]



### 3. `fit_transform`
The `fit_transform` method essentially combines the `fit` and `transform` methods into one step. It's often more efficient to use `fit_transform` on the training data rather than using `fit` and `transform` separately. However, you should be cautious about using `fit_transform` on both training and testing data for certain preprocessing techniques, as it might cause data leakage.

#### SimpleImputer example with `fit_transform`:
Here, the imputer will calculate the mean values and then immediately use them to fill the missing values.

In [26]:
data = [[1, 2], [np.nan, 3], [9, 100]]
imputer = SimpleImputer(strategy='mean')
filled_data = imputer.fit_transform(data)

print("Means:", imputer.statistics_)

print(filled_data)

Means: [ 5. 35.]
[[  1.   2.]
 [  5.   3.]
 [  9. 100.]]



### Summary:
- **`fit`**: Learns or computes properties from the data. Doesn't modify the data.
- **`transform`**: Applies a transformation or modification to the data based on what was learned during the `fit` step.
- **`fit_transform`**: Combines the two steps. Learns properties and immediately applies the transformation.

For transformers in scikit-learn, like `SimpleImputer`, the properties learned (e.g., column means) during the `fit` step are stored in instance variables (e.g., `imputer.statistics_`). This allows you to inspect what was learned, and it's also what allows the `transform` method to later apply transformations based on those learned properties.

# One Hot Encoding

One-hot encoding is a process of converting categorical data variables so they can be provided to machine learning algorithms to improve predictions. In one-hot encoding, each unique value of a categorical column is mapped to a new binary column, where each of these new columns represents a single unique value from the original column. In the new columns, the presence of the unique value is represented by a 1, while its absence is denoted by a 0. As a result, for a categorical column with n unique values, one-hot encoding will result in n new binary columns.

### Example 1: Simple DataFrame with a Single Categorical Column

**Original DataFrame:**

| Index | Color  |
|-------|--------|
| 0     | Red    |
| 1     | Green  |
| 2     | Blue   |
| 3     | Red    |

**One-hot encoded DataFrame:**

| Index | Color_Red | Color_Green | Color_Blue |
|-------|-----------|-------------|------------|
| 0     | 1         | 0           | 0          |
| 1     | 0         | 1           | 0          |
| 2     | 0         | 0           | 1          |
| 3     | 1         | 0           | 0          |

### Example 2: DataFrame with Multiple Categorical Columns

**Original DataFrame:**

| Index | Color  | Size  |
|-------|--------|-------|
| 0     | Red    | Small |
| 1     | Green  | Medium|
| 2     | Blue   | Large |
| 3     | Red    | Medium|

**One-hot encoded DataFrame:**

| Index | Color_Red | Color_Green | Color_Blue | Size_Small | Size_Medium | Size_Large |
|-------|-----------|-------------|------------|-----------|-------------|------------|
| 0     | 1         | 0           | 0          | 1         | 0           | 0          |
| 1     | 0         | 1           | 0          | 0         | 1           | 0          |
| 2     | 0         | 0           | 1          | 0         | 0           | 1          |
| 3     | 1         | 0           | 0          | 0         | 1           | 0          |

### Example 3: DataFrame with Mixed Categorical and Numeric Columns

**Original DataFrame:**

| Index | Color  | Size  | Price |
|-------|--------|-------|-------|
| 0     | Red    | Small | 10    |
| 1     | Green  | Medium| 20    |
| 2     | Blue   | Large | 30    |
| 3     | Red    | Medium| 15    |

**One-hot encoded DataFrame:**

| Index | Color_Red | Color_Green | Color_Blue | Size_Small | Size_Medium | Size_Large | Price |
|-------|-----------|-------------|------------|-----------|-------------|------------|-------|
| 0     | 1         | 0           | 0          | 1         | 0           | 0          | 10    |
| 1     | 0         | 1           | 0          | 0         | 1           | 0          | 20    |
| 2     | 0         | 0           | 1          | 0         | 0           | 1          | 30    |
| 3     | 1         | 0           | 0          | 0         | 1           | 0          | 15    |

One-hot encoding can quickly increase the dimensionality of the dataset, especially if the categorical variables have many unique values. In cases where the categorical column has a large number of categories, the one-hot encoded data can become very sparse, meaning that the majority of the values in the resulting dataframe will be zeros. This sparsity can lead to increased memory consumption, slow computation, and sometimes can even degrade the performance of certain machine learning models.

### Example: High Cardinality Categorical Column

Suppose We've a dataset that records website visits, including a user ID and the domain they visited. Let's say you have only 5 users, but they've visited a variety of 1,000 unique websites.

**Original DataFrame (only a subset shown for simplicity):**

| Index | User_ID | Domain       |
|-------|---------|--------------|
| 0     | 1       | google.com   |
| 1     | 2       | yahoo.com    |
| 2     | 3       | wikipedia.org|
| ...   | ...     | ...          |
| 999   | 5       | example.com  |

If you decide to one-hot encode the 'Domain' column:

**One-hot encoded DataFrame (only a subset of columns shown for simplicity):**

| Index | User_ID | Domain_google.com | Domain_yahoo.com | Domain_wikipedia.org | ... | Domain_example.com |
|-------|---------|------------------|-----------------|----------------------|-----|-------------------|
| 0     | 1       | 1                | 0               | 0                    | ... | 0                 |
| 1     | 2       | 0                | 1               | 0                    | ... | 0                 |
| 2     | 3       | 0                | 0               | 1                    | ... | 0                 |
| ...   | ...     | ...              | ...             | ...                  | ... | ...               |
| 999   | 5       | 0                | 0               | 0                    | ... | 1                 |

This new DataFrame has over 1,000 columns (1 for each unique website) and most of them contain a value of '0' for each record. In the full encoded DataFrame of size (1,000 x 1,001), there would be 1,000,000 entries, but only 1,000 of those would be '1' — the rest would be '0'. This means that 99.9% of the data is just zeros. This kind of sparsity can be extremely inefficient in terms of memory usage and computational performance. 

Sparse matrices, where the majority of entries are zeros, can be compressed to save space, but even with compression, extremely high dimensionality can challenge certain algorithms. For example, algorithms based on distance metrics (like k-NN) can perform poorly in high dimensions. 

In such situations, alternative encoding strategies or dimensionality reduction techniques may be considered to handle high cardinality categorical columns efficiently.

## One-Hot Encoding with Pandas - get_dummies()

In [12]:
import pandas as pd

# Example 1
df1 = pd.DataFrame({'Color': ['Red', 'Green', 'Blue', 'Red']})
print('Original DataFrame:')
display(df1)

print('\n\n')
df1_encoded = pd.get_dummies(df1, columns=['Color'], prefix=['Color'])
print('Encoded DataFrame:')
display(df1_encoded)

Original DataFrame:

   Color
0    Red
1  Green
2   Blue
3    Red

Encoded DataFrame:

   Color_Blue  Color_Green  Color_Red
0           0            0          1
1           0            1          0
2           1            0          0
3           0            0          1

In [11]:


# Example 2
df2 = pd.DataFrame({'Color': ['Red', 'Green', 'Blue', 'Red'],
                    'Size': ['Small', 'Medium', 'Large', 'Medium']})
print('Original DataFrame:')
display(df2)

print('\n\n')
df2_encoded = pd.get_dummies(df2, columns=['Color', 'Size'], prefix=['Color', 'Size'])
print('Encoded DataFrame:')
display(df2_encoded)

Original DataFrame:

   Color    Size
0    Red   Small
1  Green  Medium
2   Blue   Large
3    Red  Medium

Encoded DataFrame:

   Color_Blue  Color_Green  Color_Red  Size_Large  Size_Medium  Size_Small
0           0            0          1           0            0           1
1           0            1          0           0            1           0
2           1            0          0           1            0           0
3           0            0          1           0            1           0

In [19]:
# Example 3
df3 = pd.DataFrame({'Color': ['Red', 'Green', 'Blue', 'Red'],
                    'Size': ['Small', 'Medium', 'Large', 'Medium'],
                    'Price': [10, 20, 30, 15]})
print('Original DataFrame:')
display(df3)

print('\n\n')
df3_encoded = pd.get_dummies(df3, columns=['Color', 'Size'], prefix=['Color', 'Size'])
print('Encoded DataFrame:')
display(df3_encoded)

Original DataFrame:

   Color    Size  Price
0    Red   Small     10
1  Green  Medium     20
2   Blue   Large     30
3    Red  Medium     15

Encoded DataFrame:

,Price,Color_Blue,Color_Green,Color_Red,Size_Large,Size_Medium,Size_Small
0,10,0,0,1,0,0,1
1,20,0,1,0,0,1,0
2,30,1,0,0,1,0,0
3,15,0,0,1,0,1,0

## One-Hot Encoding with Scikit-Learn - OneHotEncoder

In [14]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()

# Example 1
df1 = pd.DataFrame({'Color': ['Red', 'Green', 'Blue', 'Red']})
print('Original DataFrame:')
display(df1)

print('\n\n')


df1_encoded = encoder.fit_transform(df1[['Color']])
df1_encoded_df = pd.DataFrame(df1_encoded.toarray(), columns=encoder.get_feature_names_out(['Color']))
print('Encoded DataFrame:')
display(df1_encoded_df)

Original DataFrame:

   Color
0    Red
1  Green
2   Blue
3    Red

Encoded DataFrame:

   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          0.0        1.0

In [15]:


# Example 2
df2 = pd.DataFrame({'Color': ['Red', 'Green', 'Blue', 'Red'],
                    'Size': ['Small', 'Medium', 'Large', 'Medium']})

print('Original DataFrame:')
display(df2)

print('\n\n')



df2_encoded = encoder.fit_transform(df2[['Color', 'Size']])
df2_encoded_df = pd.DataFrame(df2_encoded.toarray(), columns=encoder.get_feature_names_out(['Color', 'Size']))
print('Encoded DataFrame:')
display(df2_encoded_df)

Original DataFrame:

   Color    Size
0    Red   Small
1  Green  Medium
2   Blue   Large
3    Red  Medium

Encoded DataFrame:

   Color_Blue  Color_Green  Color_Red  Size_Large  Size_Medium  Size_Small
0         0.0          0.0        1.0         0.0          0.0         1.0
1         0.0          1.0        0.0         0.0          1.0         0.0
2         1.0          0.0        0.0         1.0          0.0         0.0
3         0.0          0.0        1.0         0.0          1.0         0.0

In [16]:


# Example 3
df3 = pd.DataFrame({'Color': ['Red', 'Green', 'Blue', 'Red'],
                    'Size': ['Small', 'Medium', 'Large', 'Medium'],
                    'Price': [10, 20, 30, 15]})
print('Original DataFrame:')
display(df2)

print('\n\n')




df3_encoded = encoder.fit_transform(df3[['Color', 'Size']])
df3_encoded_df = pd.DataFrame(df3_encoded.toarray(), columns=encoder.get_feature_names_out(['Color', 'Size']))
df3_encoded_df['Price'] = df3['Price']

print('Encoded DataFrame:')
display(df3_encoded_df)

Original DataFrame:

   Color    Size
0    Red   Small
1  Green  Medium
2   Blue   Large
3    Red  Medium

Encoded DataFrame:

,Color_Blue,Color_Green,Color_Red,Size_Large,Size_Medium,Size_Small,Price
0,0.0,0.0,1.0,0.0,0.0,1.0,10
1,0.0,1.0,0.0,0.0,1.0,0.0,20
2,1.0,0.0,0.0,1.0,0.0,0.0,30
3,0.0,0.0,1.0,0.0,1.0,0.0,15

# Label Encoding

Label encoding is another technique to transform categorical data into a format that machine learning algorithms can understand. Unlike one-hot encoding, which represents each category with a binary vector, label encoding represents each category with a unique number.

### Example 1: Simple DataFrame with a Single Categorical Column

**Original DataFrame:**

| Index | Color  |
|-------|--------|
| 0     | Red    |
| 1     | Green  |
| 2     | Blue   |
| 3     | Red    |

**DataFrame with Label Encoding:**

| Index | Color  | Color_encoded |
|-------|--------|---------------|
| 0     | Red    | 2             |
| 1     | Green  | 1             |
| 2     | Blue   | 0             |
| 3     | Red    | 2             |

**Mapping:**
- Red: 2
- Green: 1
- Blue: 0

### Example 2: DataFrame with Multiple Categorical Columns

**Original DataFrame:**

| Index | Color  | Size   |
|-------|--------|--------|
| 0     | Red    | Small  |
| 1     | Green  | Medium |
| 2     | Blue   | Large  |
| 3     | Red    | Medium |

**DataFrame with Label Encoding:**

| Index | Color  | Color_encoded | Size   | Size_encoded |
|-------|--------|---------------|--------|--------------|
| 0     | Red    | 2             | Small  | 2            |
| 1     | Green  | 1             | Medium | 1            |
| 2     | Blue   | 0             | Large  | 0            |
| 3     | Red    | 2             | Medium | 1            |

**Mapping:**
- Color:
  - Red: 2
  - Green: 1
  - Blue: 0
- Size:
  - Small: 2
  - Medium: 1
  - Large: 0

### Example 3: DataFrame with Mixed Categorical and Numeric Columns

**Original DataFrame:**

| Index | Color  | Size   | Price |
|-------|--------|--------|-------|
| 0     | Red    | Small  | 10    |
| 1     | Green  | Medium | 20    |
| 2     | Blue   | Large  | 30    |
| 3     | Red    | Medium | 15    |

**DataFrame with Label Encoding:**

| Index | Color  | Color_encoded | Size   | Size_encoded | Price |
|-------|--------|---------------|--------|--------------|-------|
| 0     | Red    | 2             | Small  | 2            | 10    |
| 1     | Green  | 1             | Medium | 1            | 20    |
| 2     | Blue   | 0             | Large  | 0            | 30    |
| 3     | Red    | 2             | Medium | 1            | 15    |

**Mapping:**
- Color:
  - Red: 2
  - Green: 1
  - Blue: 0
- Size:
  - Small: 2
  - Medium: 1
  - Large: 0

Having both the original and encoded columns side by side will certainly make it easier for students to see the direct mappings.

It should be noted that the integer assignments for the categories might vary depending on the implementation and ordering of categories. The above examples illustrate one possible mapping.

It's worth noting that while label encoding is more space efficient than one-hot encoding, it can introduce ordinality to the data that might not actually exist. In the above examples, there's no inherent order to colors, but the model might infer that "Blue" (encoded as 0) is somehow "less than" "Green" (encoded as 1) and "Red" (encoded as 2). For certain algorithms, this can be problematic, so it's important to consider the nature of the data and the algorithm being used when deciding between label encoding and one-hot encoding.

Of course! I'll integrate Python code samples using both `pandas` and `sklearn` into your provided content.

### Label Encoding using Pandas and Scikit-learn

Label encoding is a technique to transform categorical data into a format that machine learning algorithms can understand. Unlike one-hot encoding, which represents each category with a binary vector, label encoding represents each category with a unique number.

### Example 1: Simple DataFrame with a Single Categorical Column

**Original DataFrame:**

```python
import pandas as pd

data1 = {'Color': ['Red', 'Green', 'Blue', 'Red']}
df1 = pd.DataFrame(data1)
print(df1)
```

**DataFrame with Label Encoding using Pandas:**

```python
df1['Color_encoded'] = df1['Color'].astype('category').cat.codes
print(df1)
```

**DataFrame with Label Encoding using Scikit-learn:**

```python
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df1['Color_encoded_sklearn'] = le.fit_transform(df1['Color'])
print(df1)
```

**Mapping:**
- Red: 2
- Green: 1
- Blue: 0

In [2]:
import pandas as pd

data1 = {'Color': ['Red', 'Green', 'Blue', 'Red']}
df1 = pd.DataFrame(data1)
display(df1)

df1['Color_encoded'] = df1['Color'].astype('category').cat.codes
display(df1)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df1['Color_encoded_sklearn'] = le.fit_transform(df1['Color'])
display(df1)

   Color
0    Red
1  Green
2   Blue
3    Red

   Color  Color_encoded
0    Red              2
1  Green              1
2   Blue              0
3    Red              2

   Color  Color_encoded  Color_encoded_sklearn
0    Red              2                      2
1  Green              1                      1
2   Blue              0                      0
3    Red              2                      2

In [1]:
from sklearn.preprocessing import LabelEncoder

# Sample data
colors = ['Red', 'Green', 'Blue', 'Red']

# Initialize the encoder
le = LabelEncoder()

# Fit the encoder to the data
le.fit(colors)

# Get mappings
label_mappings = dict(zip(le.classes_, le.transform(le.classes_)))

print(label_mappings)

{'Blue': 0, 'Green': 1, 'Red': 2}


### Example 2: DataFrame with Multiple Categorical Columns

**Original DataFrame:**

```python
data2 = {'Color': ['Red', 'Green', 'Blue', 'Red'],
         'Size': ['Small', 'Medium', 'Large', 'Medium']}
df2 = pd.DataFrame(data2)
print(df2)
```

**DataFrame with Label Encoding using Pandas:**

```python
df2['Color_encoded'] = df2['Color'].astype('category').cat.codes
df2['Size_encoded'] = df2['Size'].astype('category').cat.codes
print(df2)
```

**DataFrame with Label Encoding using Scikit-learn:**

```python
le_color = LabelEncoder()
le_size = LabelEncoder()

df2['Color_encoded_sklearn'] = le_color.fit_transform(df2['Color'])
df2['Size_encoded_sklearn'] = le_size.fit_transform(df2['Size'])
print(df2)
```

**Mapping:**
- Color:
  - Red: 2
  - Green: 1
  - Blue: 0
- Size:
  - Small: 2
  - Medium: 1
  - Large: 0


### Example 3: DataFrame with Mixed Categorical and Numeric Columns

**Original DataFrame:**

```python
data3 = {'Color': ['Red', 'Green', 'Blue', 'Red'],
         'Size': ['Small', 'Medium', 'Large', 'Medium'],
         'Price': [10, 20, 30, 15]}
df3 = pd.DataFrame(data3)
print(df3)
```

**DataFrame with Label Encoding using Pandas:**

```python
df3['Color_encoded'] = df3['Color'].astype('category').cat.codes
df3['Size_encoded'] = df3['Size'].astype('category').cat.codes
print(df3)
```

**DataFrame with Label Encoding using Scikit-learn:**

```python
le_color3 = LabelEncoder()
le_size3 = LabelEncoder()

df3['Color_encoded_sklearn'] = le_color3.fit_transform(df3['Color'])
df3['Size_encoded_sklearn'] = le_size3.fit_transform(df3['Size'])
print(df3)
```

**Mapping:**
- Color:
  - Red: 2
  - Green: 1
  - Blue: 0
- Size:
  - Small: 2
  - Medium: 1
  - Large: 0

It should be noted that the integer assignments for the categories might vary depending on the implementation and ordering of categories. The above examples illustrate one possible mapping using both `pandas` and `scikit-learn`.

# Target Encoding

Target encoding, also known as mean encoding, is another method to handle categorical variables. Instead of creating new columns like in one-hot encoding or giving arbitrary numbers like in label encoding, target encoding assigns each category in a categorical column with the average target value for that category.


### Example 1: Simple DataFrame with a Single Categorical Column and a Binary Target

**Original DataFrame:**

| Index | Color  | Target |
|-------|--------|--------|
| 0     | Red    | 1      |
| 1     | Green  | 0      |
| 2     | Blue   | 1      |
| 3     | Red    | 0      |

**DataFrame with Target Encoding:**

| Index | Color  | Color_encoded |
|-------|--------|---------------|
| 0     | Red    | 0.5           |
| 1     | Green  | 0             |
| 2     | Blue   | 1             |
| 3     | Red    | 0.5           |

**Mapping:**
- Red: (1 + 0) / 2 = 0.5
- Green: 0 (since it only appears once with Target = 0)
- Blue: 1 (since it only appears once with Target = 1)

### Example 2: DataFrame with Multiple Categorical Columns and a Numeric Target

**Original DataFrame:**

| Index | Color  | Size   | Target |
|-------|--------|--------|--------|
| 0     | Red    | Small  | 10     |
| 1     | Green  | Medium | 15     |
| 2     | Blue   | Large  | 25     |
| 3     | Red    | Medium | 20     |

**DataFrame with Target Encoding:**

| Index | Color  | Color_encoded | Size   | Size_encoded |
|-------|--------|---------------|--------|--------------|
| 0     | Red    | 15            | Small  | 10           |
| 1     | Green  | 15            | Medium | 17.5         |
| 2     | Blue   | 25            | Large  | 25           |
| 3     | Red    | 15            | Medium | 17.5         |

**Mapping:**
- Color:
  - Red: (10 + 20) / 2 = 15
  - Green: 15
  - Blue: 25
- Size:
  - Small: 10
  - Medium: (15 + 20) / 2 = 17.5
  - Large: 25

### Implementation using `CategoryEncoders`:

`CategoryEncoders` is a Python library that provides several techniques for encoding categorical variables including target encoding.

```python
import pandas as pd
import category_encoders as ce

# Example data
data = pd.DataFrame({
    'Color': ['Red', 'Green', 'Blue', 'Red'],
    'Size': ['Small', 'Medium', 'Large', 'Medium'],
    'Target': [10, 15, 25, 20]
})

# Target encoder instantiation
encoder = ce.TargetEncoder(cols=['Color', 'Size'])

# Fitting and transforming the data
encoded_data = encoder.fit_transform(data[['Color', 'Size']], data['Target'])

print(encoded_data)
```

Remember, target encoding can introduce leakage if not done properly. Always encode the train and test sets separately or use techniques like cross-validation encoding to avoid potential pitfalls.


**Advantages**:
- Does not increase the dimensionality.
- Can incorporate the target information into encoding, potentially improving model performance.

**Disadvantages**:
- Prone to overfitting if not properly regularized or if the category has few occurrences.
- Introduces a relationship between the categorical column and the target, which may not always be desirable.

# Guidelines

---

### 1. **One-Hot Encoding**:

- **Description**: Converts each category value into a new column and assigns a 1 or 0 (True/False) value to the column.

- **When to Use**:
  - For nominal variables where no ordinal relationship exists.
  - With algorithms which expect orthogonal input features like linear regression.

- **Example**: For a column `Color` with values `Red`, `Blue`, and `Green`, three new columns will be created: `is_Red`, `is_Blue`, and `is_Green`. A record with `Color = Red` would have `is_Red = 1` and `is_Blue = 0` and `is_Green = 0`.

- **Advantages**:
  - Easy to interpret.
  - No introduction of arbitrary numbers, which prevents potential misinterpretation by the model.

- **Disadvantages**:
  - Can increase data dimensionality rapidly if the category has many unique values.

---

### 2. **Label Encoding**:

- **Description**: Converts each category value into a unique integer.

- **When to Use**:
  - For ordinal variables where a hierarchy or order is inherent.
  - With tree-based algorithms (like decision trees and random forests) which can interpret the ordinal nature.

- **Example**: For a column `Size` with values `Small`, `Medium`, and `Large`, these could be encoded as `0`, `1`, and `2` respectively.

- **Advantages**:
  - Efficient in terms of memory as only one column is needed.
  - Can capture the ordinal nature of certain variables.

- **Disadvantages**:
  - Introduces an arbitrary order for nominal variables.

---

### 3. **Target (Mean) Encoding**:

- **Description**: Uses the mean of the target variable for each category as its new value.

- **When to Use**:
  - When a categorical variable has high cardinality.
  - When there's a correlation between the category and the target variable.
  - Use cautiously with tree-based models.

- **Example**: If you're predicting house prices and have a categorical column `Neighborhood`, houses in the `Beverly Hills` neighborhood might have an average price of `$1M`, which becomes the encoded value for that category.

- **Advantages**:
  - Efficiently captures the relationship between category and target variable, especially for high cardinality categories.
  - Reduces dimensionality.

- **Disadvantages**:
  - Can lead to overfitting.
  - Potential for data leakage if not done properly.
  - Might introduce collinearity.

---

**Key Recommendations**:

1. **Data Splitting**: Always split your dataset into training and test sets before any encoding. This prevents information from the test set leaking into your training set.

2. **Algorithm Type**: Consider the nature of your algorithm. Linear and distance-based algorithms interpret encoded data differently compared to tree-based algorithms.

3. **Experiment**: If in doubt, experiment with different encodings and compare model performance.

4. **Be Cautious**: Particularly with target encoding, ensure you're not introducing data leakage or overfitting.

5. **Deep Learning**: For those using neural networks, consider embeddings for categorical data. It's a powerful technique, particularly for categories with many unique values.